# Generated by Django 3.2 on 2021-05-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zanry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zanr', models.CharField(blank=True, choices=[('román', 'Román'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-fi'), ('válečné', 'Válečné'), ('komiksy', 'Komiksy'), ('kuchařky', 'Kuchařky')], default='román', help_text='Vyberte žánr', max_length=20, verbose_name='Žánr')),
            ],
            options={
                'verbose_name': 'Žánr knihy',
                'verbose_name_plural': 'Žánr knihy',
                'ordering': ['zanr'],
            },
        ),
        migrations.CreateModel(
            name='Knihy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název knihy')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis knihy')),
                ('rok', models.IntegerField(help_text='Zadejte rok vydání knihy', null=True, verbose_name='Rok vydání')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='zbozi/%Y/%m/%d/', verbose_name='Fotka knihy')),
                ('zanry', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kniha.zanry')),
            ],
            options={
                'verbose_name': 'Knihy',
                'verbose_name_plural': 'Knihy',
                'ordering': ['nazev'],
            },
        ),
    ]
