# Generated by Django 3.2 on 2021-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniha', '0002_alter_zanry_zanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='knihy',
            name='autor',
            field=models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, null=True, verbose_name='Autor knihy'),
        ),
        migrations.AlterField(
            model_name='zanry',
            name='zanr',
            field=models.CharField(help_text='Zadejte text o maximální délce 20 znaků; text musí být jedinečný', max_length=20, unique=True, verbose_name='Žánr knihy'),
        ),
    ]
