# Generated by Django 3.2 on 2021-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniha', '0003_auto_20210503_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knihy',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='knihy/%Y/%m/%d/', verbose_name='Fotka knihy'),
        ),
    ]
