# Generated by Django 3.2 on 2021-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniha', '0004_alter_knihy_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='knihy',
            name='isbn',
            field=models.CharField(blank=True, help_text='Zadejte ISBN knihy', max_length=30, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='knihy',
            name='nakladatelstvi',
            field=models.CharField(blank=True, help_text='Zadejte text o maximální délce 30 znaků', max_length=30, null=True, verbose_name='Nakladatelstvi'),
        ),
        migrations.AlterField(
            model_name='knihy',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='kniha/%Y/%m/%d/', verbose_name='Fotka knihy'),
        ),
    ]
